services:
  db:
    image: postgres
    container_name: db_postgres
    environment:
      - POSTGRES_DB=Clinic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    image: backend:backend
    container_name: backend
    environment:
      - POSTGRES_NAME=Clinic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
