# Generated by Django 4.1.7 on 2023-06-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
