# Generated by Django 4.2 on 2023-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_receptionist',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
