# Generated by Django 4.2 on 2023-05-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_email_remove_employee_first_name_and_more'),
        ('patients', '0002_rename_alergies_patient_allergies_and_more'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='doses',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='visit',
        ),
        migrations.AddField(
            model_name='medicine',
            name='dose',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='recommendation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='additional_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='medicines',
            field=models.ManyToManyField(blank=True, null=True, to='visits.medicine'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='prescription_code',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='visit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patient'),
        ),
        migrations.DeleteModel(
            name='Dose',
        ),
    ]
