# Generated by Django 4.2 on 2023-05-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_function_role_rename_function_employee_role'),
        ('patients', '0003_rename_alergies_patient_allergies_alter_patient_user'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='recommendation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.recommendation'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patient'),
        ),
    ]
