# Generated by Django 4.2 on 2023-05-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_function_role_rename_function_employee_role'),
        ('visits', '0002_remove_recommendation_visit_visit_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='additional_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='medicines',
            field=models.ManyToManyField(blank=True, null=True, to='visits.medicine'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='prescription_code',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='recommendation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.recommendation'),
        ),
    ]
