# Generated by Django 4.1.7 on 2023-05-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_dose_dose_alter_medicine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
