# Generated by Django 4.2 on 2023-06-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_medicine_dose_alter_recommendation_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
