# Generated by Django 4.2 on 2023-06-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_remove_visit_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_control',
        ),
    ]
