# Generated by Django 4.2 on 2023-06-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0003_alter_medicine_dose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='medicine',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.visit'),
        ),
    ]
