# Generated by Django 4.2 on 2023-06-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_visit_visit_control_alter_visit_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_control',
            field=models.DateField(blank=True, null=True),
        ),
    ]
