# Generated by Django 4.2 on 2023-05-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_alter_recommendation_additional_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
