# Generated by Django 4.2 on 2023-05-29 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0004_visit_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='doses',
        ),
        migrations.AddField(
            model_name='medicine',
            name='dose',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Dose',
        ),
    ]
