# Generated by Django 4.1.7 on 2023-06-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_recommendation_patient'),
        ('visits', '0004_remove_recommendation_medicines_and_more'),
    ]

    operations = [
    ]
