# Generated by Django 4.2 on 2023-06-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_alter_visit_visit_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_control',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
