# Generated by Django 4.2 on 2023-06-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_alter_recommendation_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.visit'),
        ),
    ]
