# Generated by Django 4.1.7 on 2023-06-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_alter_visit_doctor'),
        ('visits', '0005_alter_visit_visit_control'),
    ]

    operations = [
    ]
