# Generated by Django 4.1.7 on 2023-06-02 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_image', models.ImageField(upload_to='employees/')),
                ('employed_at', models.DateField(null=True)),
                ('specialization', models.CharField(blank=True, choices=[('Lekarz rodzinny', 'Family Doctor'), ('Pediatra', 'Pediatrician'), ('Dermatolog', 'Dermatologist'), ('Chirurg', 'Surgeon'), ('Stomatolog', 'Dentist'), ('Ortopeda', 'Orthopaedist'), ('Internista', 'Internist')], default='', max_length=15)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.role')),
                ('title_of_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.degree')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
