# Generated by Django 4.2 on 2023-06-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_recommendation_patient_alter_visit_doctor_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
