# Generated by Django 4.2 on 2023-06-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Lekarz rodzinny', 'Family Doctor'), ('Pediatra', 'Pediatrician'), ('Dermatolog', 'Dermatologist'), ('Chirurg', 'Surgeon'), ('Stomatolog', 'Dentist'), ('Ortopeda', 'Orthopaedist'), ('Internista', 'Internist')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title_of_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.degree'),
        ),
    ]
