# Generated by Django 4.2 on 2023-06-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(choices=[('Lekarz rodzinny', 'Family Doctor'), ('Pediatra', 'Pediatrician'), ('Dermatolog', 'Dermatologist'), ('Chirurg', 'Surgeon'), ('Stomatolog', 'Dentist'), ('Ortopeda', 'Orthopaedist'), ('Internista', 'Internist')], default='Lekarz rodzinny', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Doktor', 'Doctor'), ('Recepcjonista', 'Receptionist')], default='Doktor', max_length=13),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title_of_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
