# Generated by Django 4.1.7 on 2023-06-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employed_at',
            field=models.DateField(null=True),
        ),
    ]
