# Generated by Django 4.1.7 on 2023-06-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
