# Generated by Django 4.2 on 2023-05-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time_of_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('age', models.IntegerField()),
                ('alergies', models.ManyToManyField(to='patients.allergy')),
            ],
        ),
        migrations.AddField(
            model_name='allergy',
            name='time_of_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.time_of_activity'),
        ),
    ]
