# Generated by Django 4.2 on 2023-05-07 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_of_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('time_of_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.time_of_activity')),
            ],
        ),
        migrations.AddField(
            model_name='patients',
            name='alergies',
            field=models.ManyToManyField(to='patients.allergy'),
        ),
    ]
