# Generated by Django 4.2 on 2023-06-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='patients.allergy'),
        ),
    ]
