# Generated by Django 4.2 on 2023-05-24 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_remove_patient_email_remove_patient_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='alergies',
            new_name='allergies',
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
