# Generated by Django 4.2 on 2023-05-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_time_of_activity_alter_patient_email_allergy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='pesel',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
